apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets
data:
  sonos-tools.cluster_public_root: {{ .Values.ClusterPublicRoot }}
  sonos-tools.flask_secret: {{ .Values.FlaskSecret }}
  sonos-tools.gcp_api_key: {{ .Values.GcpApiKey }}
  sonos-tools.google_auth_client_id: {{ .Values.GoogleAuthClientId }}
  sonos-tools.mongodb_connecturi: {{ .Values.MongoDBConnectUri }}
  sonos-tools.redirect_root: {{ .Values.RedirectRoot }}
  sonos-tools.sonos-api-endpoint: {{ .Values.SonosApiEndpoint }}
  sonos-tools.sonos-api-endpoint-ws: {{ .Values.SonosApiEndpointWS }}
  sonos-tools.sonosapi_appkey: {{ .Values.SonosApiAppKey }}
  sonos-tools.sonosapi_secret: {{ .Values.SonosApiAppSecret }}
  sonos-tools.env : {{ .Values.Env }}
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: secret-google-auth-clientfile
#data:
#
