apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    k8s-app: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        k8s-app: frontend
    spec:
      containers:
      - name: frontend
        image: {{.Values.DockerRepo}}/sonos-tools-{{.Values.DockerImagePrefix}}_frontend:v{{.Values.DockerImageVersion}}
        ports:
        - containerPort: 5001
          name: http
        env:
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: SONOSTOOLS_ENV
          valueFrom:
              configMapKeyRef:
                  name: secrets
                  key: sonos-tools.env
        - name: SONOSTOOLS_API_TTS_ROOT
          value: http://api-tts:5000
        - name: SONOSTOOLS_GOOGLE_AUTH_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: secrets
              key: sonos-tools.google_auth_client_id
        - name: SONOSTOOLS_MONGODB_CONNECTURI
          valueFrom:
            configMapKeyRef:
              name: secrets
              key: sonos-tools.mongodb_connecturi
        - name: SONOSTOOLS_SONOSAPI_APPKEY
          valueFrom:
            configMapKeyRef:
              name: secrets
              key: sonos-tools.sonosapi_appkey
        - name: SONOSTOOLS_SONOSAPI_SECRET
          valueFrom:
            configMapKeyRef:
              name: secrets
              key: sonos-tools.sonosapi_secret
        - name: SONOSTOOLS_FLASK_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: secrets
              key: sonos-tools.flask_secret
        - name: SONOSTOOLS_REDIRECT_ROOT 
          valueFrom:
            configMapKeyRef:
              name: secrets
              key: sonos-tools.redirect_root
        - name: SONOSTOOLS_SONOSAPI_ENDPOINT
          valueFrom:
              configMapKeyRef:
                  name: secrets
                  key: sonos-tools.sonos-api-endpoint
        - name: SONOSTOOLS_SONOSAPI_ENDPOINT_WS
          valueFrom:
              configMapKeyRef:
                  name: secrets
                  key: sonos-tools.sonos-api-endpoint-ws
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    k8s-app: frontend
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
    name: https
  selector:
    k8s-app: frontend

