version: 2

jobs:
  build:
    docker:
     - image: ubuntu
    steps:
     - checkout
     - setup_remote_docker
     - run: apt-get update && apt-get install -y git ssh
     - run: ./ci_install_docker.sh
     - run: ./ci_prepare.sh

