version: 2.1

jobs:
  build:
    docker:
     - image: ubuntu
    steps:
     - checkout
     - run: echo "${SONOSTOOLS_KUBECONFIG_BASE64}"
     - run: ./ci_prepare.sh
     - run: cat ~/.ci_tmpfiles/kube_config

