#/bin/bash

IMAGE="$SONOSTOOLS_DOCKER_REPO/sonos-tools_frontend:$1"
docker run -p 5001:5001 -it $IMAGE \
    -e SONOSTOOLS_API_TTS_ROOT=$SONOSTOOLS_API_TTS_ROOT \
    -e SONOSTOOLS_SONOSAPI_PLAYERID=$SONOSTOOLS_SONOSAPI_PLAYERID \
    -e SONOSTOOLS_GOOGLE_AUTH_CLIENT_ID=$SONOSTOOLS_GOOGLE_AUTH_CLIENT_ID \
    -e SONOSTOOLS_MONGODB_CONNECTURI=$SONOSTOOLS_MONGODB_CONNECTURI \
    -e SONOSTOOLS_SONOSAPI_APPKEY=$SONOSTOOLS_SONOSAPI_APPKEY \
    -e SONOSTOOLS_SONOSAPI_SECRET=$SONOSTOOLS_SONOSAPI_SECRET \
    -e SONOSTOOLS_REDIRECT_ROOT=$SONOSTOOLS_REDIRECT_ROOT

